[project]
name = "thebestestimator"
version = "0.1.0"
description = "A premium Version of Construction Estimation Company who help contractors to bid on more jobs by providing cost estimations & architectural services."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "python-dotenv>=1.2.2",
    "gunicorn==22.0.0",
    "requests>=2.34.2",
]
